// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using iGeoComAPI.Data;

#nullable disable

namespace iGeoComAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220427083845_CreateInitial")]
    partial class CreateInitial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("iGeoComAPI.Models.IGeoComGrabModel", b =>
                {
                    b.Property<string>("GrabId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("C_Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C_District")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C_Region")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C_area")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C_floor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C_sitename")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChineseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("E_Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("E_District")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("E_Region")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("E_area")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("E_floor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("E_sitename")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Easting")
                        .HasColumnType("float");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fax_No")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GeoNameId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<double>("Northing")
                        .HasColumnType("float");

                    b.Property<DateTime>("Rev_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subcat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tel_No")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Web_Site")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GrabId")
                        .HasName("PK_IGeoComGrabModels");

                    b.ToTable("IGeoComGrabModels");
                });

            modelBuilder.Entity("iGeoComAPI.Models.IGeoComModel", b =>
                {
                    b.Property<string>("GeoNameId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("C_Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C_District")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C_Region")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C_area")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C_floor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C_sitename")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChineseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("E_Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("E_District")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("E_Region")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("E_area")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("E_floor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("E_sitename")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Easting")
                        .HasColumnType("float");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fax_No")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Northing")
                        .HasColumnType("float");

                    b.Property<DateTime>("Rev_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subcat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tel_No")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Web_Site")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GeoNameId")
                        .HasName("PK_IGeoComModels");

                    b.ToTable("IGeoComModels");
                });
#pragma warning restore 612, 618
        }
    }
}
